//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryASSIGNMENT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class C3IT_DOTNET_TESTEntities : DbContext
    {
        public C3IT_DOTNET_TESTEntities()
            : base("name=C3IT_DOTNET_TESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MyCategory> MyCategories { get; set; }
        public virtual DbSet<myCustomer> myCustomers { get; set; }
        public virtual DbSet<MyItem> MyItems { get; set; }
        public virtual DbSet<MyOrder> MyOrders { get; set; }
        public virtual DbSet<MyUser> MyUsers { get; set; }
    }
}
